# **** At some point we need to automate the auto whitelisting of the services using some sort of cronjob or bash script for the entrypoint of the postgres file
# https://hub.docker.com/_/postgres

# **** What we are trying to do is register a cronjob using a bash entry script from postgres that creates a new cronjob for 1 minute and will execute our scripts

version: "3"

services:
    db:
        image: postgres:14.3-alpine
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - "5432"
        volumes:
            - ./data/:/var/lib/postgresql/data
            - ./scripts/on-start/:/docker-entrypoint-initdb.d
            - ./sql/:/usr/sql
        env_file: ./.env
    chainlink-fantom:
        image: smartcontract/chainlink:1.3.0
        ports:
            - "6688:6688"
        volumes:
            - ./nodes/fantom:/chainlink
        env_file: nodes/fantom/.env
        restart: always
        command: local n -a /chainlink/.creds -p /chainlink/.pass
        environment:
            - ROOT=/chainlink
            - LOG_LEVEL=debug
            - ETH_CHAIN_ID=250
            - CHAINLINK_TLS_PORT=0
            - SECURE_COOKIES=false
            - ALLOW_ORIGINS=*
            - ETH_URL=${RPC_URL}
            - DATABSE_URL=${DATABASE_URL}
        depends_on:
            - db
