version: "3"

services:
    db:
        image: postgres:14.3-alpine
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - "5432"
        volumes:
            - ./data/:/var/lib/postgresql/data
            - ./sql/:/usr/src/sql
        working_dir: /usr/src/sql
        env_file: ./.env
        command:
            - /bin/bash
            - -c
            - |
                postgres & 'while :; do sleep 6h & wait $${!}; psql dbname=${POSTGRES_DB} user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} host=localhost -f whitelist.sql; done'
                sleep infinity
    chainlink-fantom:
        image: smartcontract/chainlink:1.3.0
        ports:
            - "6688:6688"
        volumes:
            - ./nodes/fantom:/chainlink
        env_file: nodes/fantom/.env
        restart: always
        command: local n -a /chainlink/.creds -p /chainlink/.pass
        environment:
            - ROOT=/chainlink
            - LOG_LEVEL=debug
            - ETH_CHAIN_ID=250
            - CHAINLINK_TLS_PORT=0
            - SECURE_COOKIES=false
            - ALLOW_ORIGINS=*
            - ETH_URL=${RPC_URL}
            - DATABSE_URL=${DATABASE_URL}
        depends_on:
            - db

    # **** Now how do I start the service myself manually ??? - realistically it needs to run periodically to update it as required
