version: "3"

services:
    chainlink-fantom:
        image: smartcontract/chainlink:1.3.0
        ports:
            - "6688:6688"
        volumes:
            - ./nodes/fantom:/chainlink
        env_file: nodes/fantom/.env
        restart: always
        command: local n -a /chainlink/.creds -p /chainlink/.pass
        environment:
            - ROOT=/chainlink
            - LOG_LEVEL=debug
            - ETH_CHAIN_ID=250
            - CHAINLINK_TLS_PORT=0
            - SECURE_COOKIES=false
            - ALLOW_ORIGINS=*
            - ETH_URL=${RPC_URL}
            - DATABSE_URL=${DATABASE_URL}
