name: Deploy Chainlink

on:
    push:
        branches:
            - v1.0
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy Chainlink
              uses: appleboy/ssh-action@v0.1.2
              with:
                  username: ${{secrets.SSH_USERNAME}}
                  host: ${{secrets.SSH_HOST}}
                  key: ${{secrets.SSH_KEY}}
                  script: |
                      cd Chainlink-Node/
                      docker-compose down
                      git pull
                      docker-compose down
